### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by sajattack** [HaruxOS/externc-libm#2] opened 2022-06-12 06:11 UTC
Hi there, I'm looking to use libm in no_std with no_mangle, and found your crate here and a few others like it on github, but I don't see any crates.io release. Is there something I'm missing preventing a crates.io release (like a git dependency would)? Or are you opposed to it for some reason? Thanks for your work and I look forward to using it.

**Comment by HTGAzureX1212** [comment] 2022-06-12 13:26
There is absolutely nothing preventing me from publishing a release to crates.io.

It is just that it used to be for internal use for HaruxOS (now discontinued). At this point I might as well publish this crate to crates.io.

**Comment by HTGAzureX1212** [comment] 2022-06-12 13:36
The crate is now published - https://crates.io/crates/externc-libm.

Thanks for your suggestion! Assuming now that the issue is resolved, closing.

**Closed as completed by HTGAzureX1212** 2022-06-12 13:36 UTC
Labels: question

**Comment by sajattack** [comment] 2022-06-12 21:00
I actually realized I can't use this because I want to provide alternative definitions for some of the libm functions. :frowning_face: 
But I'm sure it will be useful to someone :smiling_face_with_tear:

**Comment by mothran** [comment] 2023-03-22 20:17
I apologize for for commenting on a closed issue but would you mind bumping the crates.io version with the fixes from: https://github.com/HaruxOS/externc-libm/pull/3 ?

Thanks!
